### ISSUE TITLE
Add new currencies

### ISSUE THREAD

**Issue by omergulen** [omergulen/telegram-currency-bot#3]
Add new currencies from the API's.

**Comment by norech** [comment]
Added 6 new currencies in pull request #4

**Comment by norech** [comment]
PS: Could you put a CONTRIBUTE file or make a contribution guide, it's better for contributors :)

**Comment by drowolath** [comment]
Added all currencies available on the API in pull request #5

**Comment by omergulen** [comment]
@Norech I am creating new issue :)
